# This is a basic workflow to help you get started with Actions

name: CI
on:
  schedule:
  - cron: "12 0 * * *"

  workflow_dispatch:

jobs:
  bk_fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
